# This is a basic workflow to help you get started with Actions

name: 執行PYTHON檔案TEST

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  runTest:
    runs-on:ubuntu-latest
      steps:
       - name: 檢測程式碼
         uses: actions/checkout@v4
       - name: 設置pythone環境
         uses: action/setup-python@2
         with: python-version:'3.x'
       - name: 安裝使用的套件
         run:  
         python -m pip install --upgrade pip
         pip install -r requirements.txt
       - name: 執行Unit0204Dict.py
         run:  
         python unit0204Dict.py
        
        
